package main

import (
	"fmt"
	"github.com/gocolly/colly"
	"github.com/tidwall/gjson"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

type List struct {
	Name string
	Id   string
}

type fn func(string) []List

func main() {
	data := `// Autogenerated by retrieve.go. DO NOT EDIT.
	package libmozhi`
	data = data + DataGenerator(LangListGoogle, "langListGoogle")
	data = data + DataGenerator(LangListDeepl, "langListDeepl")
	data = data + DataGenerator(LangListMyMemory, "langListMyMemory")
	// Captcha appears too often, so I can't auto-scrape this realistically
	//data = data + DataGenerator(LangListYandex, "langListYandex")
	// If I had a reliable libretranslate instance, I would add this programatically as well, but unfortunately I don't
	//data = data + DataGenerator(LangListLibreTranslate, "langListLibreTranslate")
	fmt.Println(data)
}

func DataGenerator(LangListFunc fn, GeneratedFuncName string) string {
	// FIXME: This is jank as hell, I need to refactor this later
	SL := LangListFunc("sl")
	TL := LangListFunc("tl")
	var formattedSL string
	var formattedTL string
	for _, i := range SL {
		formattedSL = formattedSL + `{ Id: "` + i.Id + `", Name: "` + i.Name + `",},`
	}
	for _, i := range TL {
		formattedTL = formattedTL + `{ Id: "` + i.Id + `", Name: "` + i.Name + `",},`
	}
	data := `
	func ` + GeneratedFuncName + `(listType string) []List {
		ListDataSL := []List{`
	data = data + formattedSL
	data = data + `}
		ListDataTL := []List{`
	data = data + formattedTL
	data = data + `}
		if listType == "sl" {
			return ListDataSL
		} else {
			return ListDataTL
		}
	}`
	return data
}

func LangListGoogle(listType string) []List {
	UserAgent, ok := os.LookupEnv("MOZHI_USER_AGENT")
	if !ok {
		UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
	}
	sc := colly.NewCollector(colly.AllowedDomains("translate.google.com"), colly.UserAgent(UserAgent))
	var ListData []List
	sc.OnHTML("body", func(e *colly.HTMLElement) {
		e.ForEach("div.language-item", func(i int, el *colly.HTMLElement) {
			var ListInfo List
			ListInfo.Name = el.ChildText("a")
			if listType == "tl" {
				ListInfo.Id = strings.TrimPrefix(strings.TrimSuffix(el.ChildAttr("a", "href"), "&hl=en-US"), "./m?sl=en&tl=")
			} else {
				ListInfo.Id = strings.TrimPrefix(strings.TrimSuffix(el.ChildAttr("a", "href"), "&tl=en&hl=en-US"), "./m?sl=")
			}
			ListData = append(ListData, ListInfo)
		})
	})
	url := "https://translate.google.com/m?sl=en&tl=en&hl=en-US&mui=" + listType
	sc.Visit(url)
	return ListData
}
func LangListLibreTranslate(listType string) []List {
	// TODO: Make it configurable
	//libreTranslateOut := PostRequest("https://translate.argosopentech.com/languages", []byte(""))
	req, err := http.NewRequest("GET", "https://translate.terraprint.co/languages", nil)
	if err != nil {
		fmt.Println(err)
	}
	client := &http.Client{}
	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
	}

	defer res.Body.Close()

	body, err := io.ReadAll(res.Body)
	if err != nil {
		fmt.Println(err)
	}

	bodyStr := string(body)

	if !gjson.Valid(bodyStr) {
		return []List{}
	}
	gjsonArr := gjson.Parse(bodyStr).Array()
	var ListData []List
	for _, r := range gjsonArr {
		code := r.Get("code").String()
		name := r.Get("name").String()

		ListData = append(ListData, List{Id: code, Name: name})
	}
	if listType == "sl" {
		auto := List{
			Id:   "auto",
			Name: "Detect Language",
		}
		ListData = append(ListData, auto)
	}
	return ListData
}
func LangListYandex(listType string) []List {
	UserAgent, ok := os.LookupEnv("MOZHI_USER_AGENT")
	if !ok {
		UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
	}
	sc := colly.NewCollector(colly.AllowedDomains("localhost:8000"), colly.UserAgent(UserAgent))
	var ListData []List
	sc.OnHTML("table.langs", func(e *colly.HTMLElement) {
		if listType == "sl" {
			e.ForEach("select[name='from'] option", func(i int, el *colly.HTMLElement) {
				var ListInfo List
				ListInfo.Name = el.Text
				ListInfo.Id = el.Attr("value")
				ListData = append(ListData, ListInfo)
			})
		} else {
			e.ForEach("select[name='to'] option", func(i int, el *colly.HTMLElement) {
				var ListInfo List
				ListInfo.Name = el.Text
				ListInfo.Id = el.Attr("value")
				ListData = append(ListData, ListInfo)
			})

		}
	})
	//url := "https://translate.yandex.com/index.html"
	// Static version of translate.yandex.com/index.html nojs/mobile version (you can get to it by using UBO and disabling JS). Need this to bypass captcha
	url := "http://localhost:8000/index.html"
	sc.Visit(url)
	return ListData
}

func LangListDeepl(listType string) []List {
	r, _ := http.NewRequest("GET", "https://deepl.com/translator", nil)

	UserAgent := "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
	r.Header.Set("User-Agent", UserAgent)

	client := &http.Client{}
	res, _ := client.Do(r)

	defer res.Body.Close()

	body, _ := io.ReadAll(res.Body)
	var listTypeBig string
	if listType == "sl" {
		listTypeBig = "source"
	} else if listType == "tl" {
		listTypeBig = "target"
	}
	re := regexp.MustCompile(`selectLang_` + listTypeBig + `_(..)'] = '(.*)'`)
	match := re.FindAllStringSubmatch(string(body), -1)
	var ListData []List
	for i := range match {
		var ListInfo List
		ListInfo.Name = match[i][2]
		ListInfo.Id = match[i][1]
		ListData = append(ListData, ListInfo)
	}
	if listType == "tl" {
		ListData = append(ListData, List{Id: "pt-br", Name: "Portugese (Brazillian)"})
		ListData = append(ListData, List{Id: "pt-pt", Name: "Portugese (Non-Brazillian)"})
		ListData = append(ListData, List{Id: "zh-hans", Name: "Chinese (Simplified)"})
		ListData = append(ListData, List{Id: "zh-hant", Name: "Chinese (Traditional)"})
		ListData = append(ListData, List{Id: "en-us", Name: "Portugese (American)"})
		ListData = append(ListData, List{Id: "en-gb", Name: "Portugese (British)"})
	}
	return ListData
}

func LangListMyMemory(listType string) []List {
	req, err := http.NewRequest("GET", "https://www.matecat.com/api/v2/languages", nil)
	if err != nil {
		fmt.Println(err)
	}
	client := &http.Client{}
	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
	}

	defer res.Body.Close()

	body, err := io.ReadAll(res.Body)
	if err != nil {
		fmt.Println(err)
	}

	bodyStr := string(body)

	if !gjson.Valid(bodyStr) {
		return []List{}
	}
	gjsonArr := gjson.Parse(bodyStr).Array()
	var ListData []List
	for i, r := range gjsonArr {
		code := r.Get("code").String()
		name := r.Get("name").String()
		codeSmall := strings.Split(code, "-")[0]
		// If previous or next value is also the same language, then dont remove the trailing characters
		if i > 0 && i < len(gjsonArr)-1 {
			if (strings.Split(gjsonArr[i+1].Get("code").String(), "-")[0] == codeSmall || strings.Split(gjsonArr[i-1].Get("code").String(), "-")[0] == codeSmall) {
				codeSmall = code
			}
		}
		ListData = append(ListData, List{Id: codeSmall, Name: name})
	}
	if listType == "sl" {
		auto := List{
			Id:   "auto",
			Name: "Detect Language",
		}
		ListData = append(ListData, auto)
	}
	return ListData
}

// TODO: Scrape DuckDuckGo & Reverso Language Lists
